export const artists = [
    "coez",
    "rkomi",
    "willie peyote",
    "ernia",
    "carl brave",
    "frah quintale",
    "franco126",
    "lowlow",
    "tredici pietro",
    "rovere",
    "calcutta ",
    "ariete",
    "fulminacci",
    "galeffi",
    "legno",
    "mecna",
    "tananai",
    "psicologi",
    "canova",
    "mobrici",
    "bnkr44",
    "ex-otago",
    "fast animals and slow kids",
    "giorgio poi",
    "svegliaginevra",
    "gazzelle",
    "duth nazari",
    "laila al habash",
    "labadessa",
    "caterina",
    "la rappresentante di lista",
    "coma_cose",
    "peter white",
    "venerus",
    "lo stato sociale",
    "pinguini tattici nucleari",
    "svegliaginevra",
    "drast",
    "cimini",
    "dente",
    "tropico",
    "l'officina della camomilla",
    "lil kvneki",
    "dile",
    "ciliari",
    "aiello",
    "cosmo",
    "carl brave x franco126",
    "viito",
    "brunori sas",
    "eugenio in via di gioia",
    "i cani",
    "ceri",
    "joan thiele",
    "ibris 37",
    "masamasa",
    "m.e.r.l.o.t",
    "fiat131",
    "chiello",
    "clavdio",
    "gianmaria",
    "anzj"
]